######################################################################
# Automatically generated by qmake (1.07a) Mon Apr 12 21:12:21 2004
######################################################################


# Input
















































TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= qt warn_on release


SOURCES	+= main.cpp
FORMS	= form1.ui

